version: "2"
services:
 column-db:
   container_name: column-db
   image: librairy/column-db:1.3
   restart: always
   volumes: ["./columndb:/var/lib/cassandra"]
   ports: ["9160:9160","9042:9042"]
#   environment: ["CASSANDRA_LISTEN_ADDRESS=127.0.0.1","CASSANDRA_RPC_ADDRESS=127.0.0.1"]
   mem_limit: 12g
   memswap_limit: 14g
   cpuset: 0,1
   networks: ["lnet"]
 document-db:
   container_name: document-db
   image: librairy/document-db:1.0
   restart: always
   volumes: ["./documentdb:/usr/share/elasticsearch/data"]
   ports: ["9200:9200","9300:9300"]
   environment: ["ES_JAVA_OPTS=-Xms4g -Xmx4g"]
   mem_limit: 6g
   memswap_limit: 8g
   cpuset: 2,3
   ulimits:
    nofile:
     soft: 65536
     hard: 65536
   networks: ["lnet"]
 graph-db:
   container_name: graph-db
   image: librairy/graph-db:1.2
   restart: always
   volumes: ["./graphdb:/data"]
   ports: ["7474:7474"]
   mem_limit: 6g
   memswap_limit: 8g
   cpuset: 4,5
   environment: ["NEO4J_HEAP_MEMORY=4096","NEO4J_CACHE_MEMORY=2G"]
   ulimits:
    nofile:
     soft: 65536
     hard: 65536
   networks: ["lnet"]
 event-bus:
   container_name: event-bus
   image: librairy/event-bus:1.0
   restart: always
   ports: ["5672:5672","15672:15672"]
   environment: ["RABBITMQ_HIPE_COMPILE=1"]
   mem_limit: 2g
   memswap_limit: 4g
   cpuset: 6,7
   networks: ["lnet"]
networks:
  lnet:
