version: "2"
services:
 column-db:
   container_name: column-db
   image: librairy/column-db:1.6
   restart: always
   volumes: ["./columndb:/var/lib/cassandra"]
   ports: ["9160:9160","9042:9042"]
   environment: ["MAX_HEAP_SIZE=16G","HEAP_NEWSIZE=3200M"]
#   mem_limit: 4g
#   memswap_limit: 6g
#   cpuset: 0-4
   ulimits:
    nofile:
     soft: 100000
     hard: 100000
#   network_mode: host
   networks: ["lnet"]
 document-db:
   container_name: document-db
   image: librairy/document-db:1.0
   restart: always
   volumes: ["./documentdb:/usr/share/elasticsearch/data"]
   ports: ["9200:9200","9300:9300"]
#   environment: ["ES_JAVA_OPTS=-Xms4g -Xmx4g"]
#   mem_limit: 6g
#   memswap_limit: 8g
#   cpuset: 2,3
   ulimits:
    nofile:
     soft: 65536
     hard: 65536
#   network_mode: host
   networks: ["lnet"]
 graph-db:
   container_name: graph-db
   image: librairy/graph-db:1.2
   restart: always
   volumes: ["./graphdb:/data"]
   ports: ["7474:7474"]
#   mem_limit: 6g
#   memswap_limit: 8g
#   cpuset: 4,5
   environment: ["NEO4J_HEAP_MEMORY=1024","NEO4J_CACHE_MEMORY=1G"]
   ulimits:
    nofile:
     soft: 65536
     hard: 65536
#   network_mode: host
   networks: ["lnet"]
 event-bus:
   container_name: event-bus
   image: librairy/event-bus:1.0
   restart: always
   environment: ["RABBITMQ_HIPE_COMPILE=1"]
   ports: ["5672:5672","15672:15672"]
#   mem_limit: 2g
#   memswap_limit: 4g
#   cpuset: 6,7
#   network_mode: host
   networks: ["lnet"]
networks:
  lnet: