version: "2"
services:
 modeler-lda:
  container_name: modeler-lda
  image: librairy/modeler-lda:1.4.1
  restart: always
  env_file: ../librairy.env
  environment:
   - JAVA_OPTS=-Xmx64g -Xms512m
  volumes: ["../models:/librairy/domains"]
  mem_limit: 66048m
#  memswap_limit: 18g
  cpuset: 4-19
  ulimits:
    nofile:
     soft: 100000
     hard: 100000
  ports: ["9040:4040"]
#  network_mode: host
  external_links:
   - column-db
   - document-db
   - graph-db
   - event-bus
  networks:
   - "lnet"
networks:
  lnet:
   external:
    name: storage_lnet