version: "2"
services:
 modeler-lda:
  container_name: modeler-lda
  image: librairy/modeler-lda:0.38
  restart: always
  env_file: ../librairy.env
  volumes: ["./models:/librairy/domains"]
  mem_limit: 16g
  memswap_limit: 18g
  cpuset: 5-11
  ports: ["4040:4040"]
  external_links:
   - column-db
   - document-db
   - graph-db
   - event-bus
  networks:
   - "lnet"
networks:
  lnet:
   external:
    name: storage_lnet
