
version: "2"
services:
 explorer-bluebottle:
  container_name: explorer-bluebottle
  image: jluisred/explorer-bluebottle
  env_file: ../librairy.env
  mem_limit: 6g
  memswap_limit: 8g
  cpuset: "11"
  expose:
     - "8888"
  ports:
     - "0.0.0.0:8888:8888"
  external_links:
   - column-db
   - document-db
   - graph-db
   - event-bus
  networks:
   - "lnet"
networks:
  lnet:
   external:
    name: storage_lnet

