version: "2"
services:
 modeler-lda:
  container_name: web
  image: librairy/web:1.0
  restart: always
  env_file: ../librairy.env
  environment:
   - LIBRAIRY_DEBUG=0
   - LIBRAIRY_CACHE_ENABLED=0
   - LIBRAIRY_SERVICE_IP=api
   - LIBRAIRY_SERVICE_PORT=80
#  mem_limit: 32g
#  memswap_limit: 34g
#  cpuset: 8-11
  ports: ["9090:8080"]
  external_links:
   - api
#  network_mode: host
  networks:
   - "lnet"
networks:
  rest:
   external:
    name: api_rest