version: "2"
services:
 tokenizer:
  container_name: tokenizer
  image: librairy/annotator-tokenizer:0.5
  restart: always
  env_file: ../librairy.env
  mem_limit: 6g
  memswap_limit: 8g
  cpuset: 8,9,10
  external_links:
   - column-db
   - document-db
   - graph-db
   - event-bus
  networks: ["lnet"]
networks:
  lnet:
   external:
    name: storage_lnet
