version: '2'
services:
  bus:
    mem_limit: 536870912
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: librairy
      RABBITMQ_DEFAULT_VHOST: librairy
      RABBITMQ_DEFAULT_PASS: l1brA1ry
    stdin_open: true
    memswap_limit: 1073741824
    labels:
      io.rancher.scheduler.affinity:host_label: environment=node1
      environment: node1
      io.rancher.container.pull_image: always
  linker:
    mem_limit: 3288334336
    image: librairy/linker-jsd:1.8.6
    environment:
      LIBRAIRY_URI: zavijava.librairy.linkeddata.es/resources
      JAVA_OPTS: -Xmx3072m -Xms64m
      LIBRAIRY_COMPUTING_CACHE: MEMORY_AND_DISK
      LIBRAIRY_COMPUTING_CLUSTER: local[3]
      LIBRAIRY_JSD_SCORE_MIN: '0.9'
      LIBRAIRY_JSD_SIZE_MAX: '500'
      LIBRAIRY_JSD_SIZE_MIN: '5'
      LIBRAIRY_COLUMNDB_HOST: librairy-db2,librairy-db1
    stdin_open: true
    links:
    - db2:librairy-db2
    - bus:librairy-bus
    - db1:librairy-db1
    memswap_limit: 6576668672
    labels:
      io.rancher.scheduler.affinity:host_label: environment=node2
      environment: node2
      io.rancher.container.pull_image: always
  db1:
    mem_limit: 2365587456
    image: cassandra:3.10
    hostname: librairy-db1
    environment:
      JAVA_OPTS: -XX:+AlwaysPreTouch
      MAX_HEAP_SIZE: 1024M
      HEAP_NEWSIZE: 256M
      CASSANDRA_CLUSTER_NAME: librairy_cluster
      CASSANDRA_SEEDS: librairy-db1
    stdin_open: true
    volumes:
    - /mnt/librairy/data/n1:/var/lib/cassandra
    cpuset: 2-3
    memswap_limit: 4731174912
    command:
    - bash
    - -c
    - if [ -z "$$$$(ls -A /var/lib/cassandra/)" ] ; then sleep 0; fi && /docker-entrypoint.sh cassandra -f
    labels:
      io.rancher.scheduler.affinity:host_label: environment=node1
      environment: node1
      io.rancher.container.pull_image: always
  db2:
    image: cassandra:3.10
    stdin_open: true
    volumes:
    - /mnt/librairy/data/n2:/var/lib/cassandra
    cpuset: 2-3
    command:
    - bash
    - -c
    - if [ -z "$$$$(ls -A /var/lib/cassandra/)" ] ; then sleep 60; fi && /docker-entrypoint.sh cassandra -f
    labels:
      io.rancher.scheduler.affinity:host_label: environment=node2
      environment: node2
      io.rancher.container.pull_image: always
    mem_limit: 2365587456
    hostname: librairy-db2
    environment:
      JAVA_OPTS: -XX:+AlwaysPreTouch
      MAX_HEAP_SIZE: 1024M
      HEAP_NEWSIZE: 256M
      CASSANDRA_CLUSTER_NAME: librairy_cluster
      CASSANDRA_SEEDS: librairy-db1
    links:
    - db1:librairy-db1
    memswap_limit: 4731174912
  api2:
    mem_limit: 562036736
    image: librairy/api:1.8.8
    environment:
      LIBRAIRY_URI: zavijava.librairy.linkeddata.es/resources
      JAVA_OPTS: -Xmx512m -Xms32m
      LIBRAIRY_API_USERS: bb:8d594825
      LIBRAIRY_COLUMNDB_HOST: librairy-db2,librairy-db1
    stdin_open: true
    cpuset: '3'
    links:
    - db2:librairy-db2
    - bus:librairy-bus
    - db1:librairy-db1
    memswap_limit: 1124073472
    labels:
      io.rancher.scheduler.affinity:host_label: environment=node2
      environment: node2
      io.rancher.container.pull_image: always
  tokenizer1:
    mem_limit: 4362076160
    image: librairy/annotator-tokenizer:1.8.5.2
    environment:
      LIBRAIRY_URI: zavijava.librairy.linkeddata.es/resources
      JAVA_OPTS: -Xmx4096m -Xms32m
      LIBRAIRY_COLUMNDB_HOST: librairy-db1,librairy-db2
      LIBRAIRY_TOKENIZER_MAX_PARALLEL: '3'
    stdin_open: true
    cpuset: 0-2
    links:
    - db2:librairy-db2
    - bus:librairy-bus
    - db1:librairy-db1
    memswap_limit: 8724152320
    labels:
      io.rancher.scheduler.affinity:host_label: environment=node1
      environment: node1
      io.rancher.container.pull_image: always
  tokenizer2:
    mem_limit: 4362076160
    image: librairy/annotator-tokenizer:1.8.5.2
    environment:
      LIBRAIRY_URI: zavijava.librairy.linkeddata.es/resources
      JAVA_OPTS: -Xmx4096m -Xms32m
      LIBRAIRY_COLUMNDB_HOST: librairy-db2,librairy-db1
      LIBRAIRY_TOKENIZER_MAX_PARALLEL: '3'
    stdin_open: true
    cpuset: 0-2
    links:
    - db2:librairy-db2
    - bus:librairy-bus
    - db1:librairy-db1
    memswap_limit: 8724152320
    labels:
      io.rancher.scheduler.affinity:host_label: environment=node2
      environment: node2
      io.rancher.container.pull_image: always
  lda:
    mem_limit: 3288334336
    image: librairy/modeler-lda:1.8.3.4
    environment:
      LIBRAIRY_URI: zavijava.librairy.linkeddata.es/resources
      JAVA_OPTS: -Xmx3072m -Xms64m
      LIBRAIRY_COMPUTING_CACHE: MEMORY_AND_DISK
      LIBRAIRY_COMPUTING_CLUSTER: local[4]
      LIBRAIRY_COLUMNDB_HOST: librairy-db1,librairy-db2
      LIBRAIRY_LDA_MAX_PENDING_SHAPES: '1000'
    stdin_open: true
    volumes:
    - /mnt/librairy/models:/librairy/domains
    links:
    - bus:librairy-bus
    - db2:librairy-db2
    - db1:librairy-db1
    memswap_limit: 6576668672
    labels:
      io.rancher.scheduler.affinity:host_label: environment=node1
      environment: node1
      io.rancher.container.pull_image: always
  api-lb:
    image: rancher/lb-service-haproxy:v0.7.5
    ports:
    - 8080:8080/tcp
    - 9942:9942/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: environment=node1
      io.rancher.container.agent.role: environmentAdmin
      environment: node1
      io.rancher.container.create_agent: 'true'
  api1:
    mem_limit: 562036736
    image: librairy/api:1.8.8
    environment:
      LIBRAIRY_URI: zavijava.librairy.linkeddata.es/resources
      JAVA_OPTS: -Xmx512m -Xms32m
      LIBRAIRY_API_USERS: bb:8d594825
      LIBRAIRY_COLUMNDB_HOST: librairy-db1,librairy-db2
    stdin_open: true
    cpuset: '3'
    links:
    - bus:librairy-bus
    - db2:librairy-db2
    - db1:librairy-db1
    memswap_limit: 1124073472
    labels:
      io.rancher.scheduler.affinity:host_label: environment=node1
      environment: node1
      io.rancher.container.pull_image: always
  harvester-bb:
    mem_limit: 562036736
    image: librairy/harvester-bluebottle:1.3.1
    environment:
      DOMAIN_CONF: BlueBottle
      LIBRAIRY_EXPLORER_DOMAIN_ID: blueBottle
      MIN_CHAPTER_LENGTH: '2500'
      LIBRAIRY_HARVESTER_ENDPOINT_CLIENT: http://api.staging.bluebottlebiz.com/
      LIBRAIRY_HARVESTER_ENDPOINT_CLIENT_APIKEY: e62f85c0-8ed2-11e6-96d5-b8aeed74afe3
      LIBRAIRY_HARVESTER_ENDPOINT_LIBRAIRY: http://librairy-api:8080/api/
      LIBRAIRY_HARVESTER_CORPUS_NAME: blueBottle
      LIBRAIRY_HARVESTER_CACHE_ENABLED: '1'
      LIBRAIRY_HARVESTER_LOAD_GT: '0'
      LIBRAIRY_HARVESTER_TOKENIZER_MODE: lemma
      LIBRAIRY_HARVESTER_LDA_DELAY: '60000'
      LIBRAIRY_HARVESTER_FORCE_PAGE: '0'
      LIBRAIRY_HARVESTER_PARALLEL_PROCESSING: '1'
      LIBRAIRY_HARVESTER_TOPICS: '15'
      JAVA_OPTS: -Xmx512m -Xms64m
      LIBRAIRY_HARVESTER_USER_LIBRAIRY: bb:8d594825
    stdin_open: true
    volumes:
    - /mnt/librairy/harvester:/cache
    links:
    - api-lb:librairy-api
    memswap_limit: 1124073472
    labels:
      io.rancher.scheduler.affinity:host_label: environment=nodex
      io.rancher.container.start_once: 'true'
      environment: nodex
      io.rancher.container.pull_image: always
