version: '2'
services:
  bus:
    milli_cpu_reservation: 200
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 5672
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  linker:
    milli_cpu_reservation: 500
    scale: 1
    start_on_create: true
  lda:
    milli_cpu_reservation: 500
    scale: 1
    start_on_create: true
  api-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: tcp
        service: api
        source_port: 8080
        target_port: 8080
      - priority: 2
        protocol: tcp
        service: api
        source_port: 9942
        target_port: 9942
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  api:
    milli_cpu_reservation: 200
    scale: 2
    start_on_create: true
  harvester-bb:
    milli_cpu_reservation: 100
    scale: 1
    start_on_create: true
  db:
    milli_cpu_reservation: 1000
    scale: 1
    start_on_create: true
  tokenizer:
    milli_cpu_reservation: 900
    scale: 1
    start_on_create: true
