version: '2'
services:
  bus:
    scale: 1
    start_on_create: true
  linker:
    scale: 1
    start_on_create: true
  db1:
    scale: 1
    start_on_create: true
  db2:
    scale: 1
    start_on_create: true
  api2:
    scale: 1
    start_on_create: true
  tokenizer1:
    scale: 1
    start_on_create: true
  tokenizer2:
    scale: 1
    start_on_create: true
  lda:
    scale: 1
    start_on_create: true
  api-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: tcp
        service: api1
        source_port: 8080
        target_port: 8080
      - priority: 3
        protocol: tcp
        service: api1
        source_port: 9942
        target_port: 9942
      - priority: 4
        protocol: tcp
        service: api2
        source_port: 8080
        target_port: 8080
      - priority: 5
        protocol: tcp
        service: api2
        source_port: 9942
        target_port: 9942
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  api1:
    scale: 1
    start_on_create: true
  harvester-bb:
    scale: 1
    start_on_create: true
