version: "2"
services:
 librairy-rhetoric1:
   container_name: librairy-rhetoric1
   image: librairy/annotator-rhetoric:1.8.0
   restart: always
   environment:
    - LIBRAIRY_URI=minetur.dia.fi.upm.es:9999/api
    - JAVA_OPTS=-Xmx8g -Xms512m
    - LIBRAIRY_COLUMNDB_HOST=minetur.dia.fi.upm.es
    - LIBRAIRY_EVENTBUS_HOST=minetur.dia.fi.upm.es
   mem_limit: 8320m
   memswap_limit: 8320m
   cpuset: 14-16
 librairy-rhetoric2:
    container_name: librairy-rhetoric2
    image: librairy/annotator-rhetoric:1.8.0
    restart: always
    environment:
     - LIBRAIRY_URI=minetur.dia.fi.upm.es:9999/api
     - JAVA_OPTS=-Xmx8g -Xms512m
     - LIBRAIRY_COLUMNDB_HOST=minetur.dia.fi.upm.es
     - LIBRAIRY_EVENTBUS_HOST=minetur.dia.fi.upm.es
    mem_limit: 8320m
    memswap_limit: 8320m
    cpuset: 16-18
 librairy-rhetoric3:
    container_name: librairy-rhetoric3
    image: librairy/annotator-rhetoric:1.8.0
    restart: always
    environment:
     - LIBRAIRY_URI=minetur.dia.fi.upm.es:9999/api
     - JAVA_OPTS=-Xmx8g -Xms512m
     - LIBRAIRY_COLUMNDB_HOST=minetur.dia.fi.upm.es
     - LIBRAIRY_EVENTBUS_HOST=minetur.dia.fi.upm.es
    mem_limit: 8320m
    memswap_limit: 8320m
    cpuset: 18-20
 librairy-rhetoric4:
    container_name: librairy-rhetoric1
    image: librairy/annotator-rhetoric:1.8.0
    restart: always
    environment:
     - LIBRAIRY_URI=minetur.dia.fi.upm.es:9999/api
     - JAVA_OPTS=-Xmx8g -Xms512m
     - LIBRAIRY_COLUMNDB_HOST=minetur.dia.fi.upm.es
     - LIBRAIRY_EVENTBUS_HOST=minetur.dia.fi.upm.es
    mem_limit: 8320m
    memswap_limit: 8320m
    cpuset: 20-22
 librairy-rhetoric5:
    container_name: librairy-rhetoric1
    image: librairy/annotator-rhetoric:1.8.0
    restart: always
    environment:
     - LIBRAIRY_URI=minetur.dia.fi.upm.es:9999/api
     - JAVA_OPTS=-Xmx8g -Xms512m
     - LIBRAIRY_COLUMNDB_HOST=minetur.dia.fi.upm.es
     - LIBRAIRY_EVENTBUS_HOST=minetur.dia.fi.upm.es
    mem_limit: 8320m
    memswap_limit: 8320m
    cpuset: 22-24