version: "2"
services:
 harvester-bluebottle:
  container_name: harvester-bluebottle
  image: jluisred/harvester-bluebottle
  env_file: ../librairy.env
  mem_limit: 3g
  #memswap_limit: 8g
  cpuset: 8-9
  external_links:
   - column-db
   - document-db
   - graph-db
   - event-bus
   - librairy-api
  networks:
   - "lnet"
networks:
  lnet:
   external:
    name: storage_lnet