version: "2"
services:
 librairy-tokenizer:
   container_name: librairy-tokenizer
   image: librairy/annotator-tokenizer:1.8.0
   restart: always
   environment:
    - LIBRAIRY_URI=librairy.linkeddata.es/resources
    - JAVA_OPTS=-Xmx30g -Xms512m
 #   - LIBRAIRY_COLUMNDB_HOST=minetur.dia.fi.upm.es
 #   - LIBRAIRY_EVENTBUS_HOST=minetur.dia.fi.upm.es
   mem_limit: 30848m
   memswap_limit: 30848m
   cpuset: 4-14
   external_links:
    - librairy-db
    - librairy-bus
   networks:
    - lnet
networks:
 lnet:
  external:
   name: core_lnet