version: "2"
services:
 librairy-jsd:
   container_name: librairy-jsd
   image: librairy/linker-jsd:1.8.0
   restart: always
   environment:
    - LIBRAIRY_URI=librairy.linkeddata.es/resources
    - LIBRAIRY_JSD_SCORE_MIN=0.5
    - LIBRAIRY_COMPUTING_CLUSTER=local[10]
    - LIBRAIRY_JSD_SCORE_MIN=0.7
 #   - JAVA_OPTS=-Xmx30g -Xms512m
 #   - LIBRAIRY_COLUMNDB_HOST=minetur.dia.fi.upm.es
 #   - LIBRAIRY_EVENTBUS_HOST=minetur.dia.fi.upm.es
 #  mem_limit: 30848m
 #  memswap_limit: 30848m
 #  cpuset: 4-14
   external_links:
    - librairy-db
    - librairy-bus
   networks:
    - lnet
networks:
 lnet:
  external:
   name: core_lnet