version: "2"
services:
 librairy-tokenizer:
   container_name: librairy-tokenizer
   image: librairy/annotator-tokenizer:1.8.0
   restart: always
   environment:
    - LIBRAIRY_URI=librairy/api
    - JAVA_OPTS=-Xmx60g -Xms512m
    #- LIBRAIRY_COLUMNDB_HOST=librairy-db
    #- LIBRAIRY_EVENTBUS_HOST=librairy-bus
   mem_limit: 61952m
   memswap_limit: 61952m
   cpuset: 2-32
   external_links:
    - librairy-db
    - librairy-bus
   networks:
    - lnet
 librairy-lda:
   container_name: librairy-lda
   image: librairy/modeler-lda:1.8.0
   restart: always
   environment:
    - LIBRAIRY_URI=librairy/api
    - JAVA_OPTS=-Xmx60g -Xms512m
    - LIBRAIRY_COMPUTING_CACHE=MEMORY_ONLY_SER
    - LIBRAIRY_COMPUTING_CLUSTER=local[30]
    #- LIBRAIRY_COLUMNDB_HOST=librairy-db
    #- LIBRAIRY_EVENTBUS_HOST=librairy-bus
   volumes:
    - ./librairy-models:/librairy/domains
   mem_limit: 61952m
   memswap_limit: 61952m
   cpuset: 2-32
   ulimits:
    nofile: 100000
   external_links:
    - librairy-db
    - librairy-bus
   networks:
    - lnet
 librairy-jsd:
   container_name: librairy-jsd
   image: librairy/linker-jsd:1.8.0
   restart: always
   environment:
    - LIBRAIRY_URI=librairy/api
    - JAVA_OPTS=-Xmx8g -Xms512m
    #- LIBRAIRY_COLUMNDB_HOST=librairy-db
    #- LIBRAIRY_EVENTBUS_HOST=librairy-bus
   mem_limit: 8320m
   memswap_limit: 8320m
   cpuset: 2-32
   external_links:
    - librairy-db
    - librairy-bus
   networks:
    - lnet
networks:
  lnet:
   external:
    name: core_lnet