version: "2"
services:
 modeler-lda:
  container_name: api
  image: librairy/api:1.6
  restart: always
  env_file: ../librairy.env
  environment:
   - JAVA_OPTS=-Xmx8g -Xms8g
  volumes: ["../models:/librairy/domains"]
#  mem_limit: 6g
#  memswap_limit: 8g
#  cpuset: 8-11
  ulimits:
      nofile:
       soft: 100000
       hard: 100000
  ports: ["80:8080","4042:4040"]
  network_mode: host
#  external_links:
#   - column-db
#   - document-db
#   - graph-db
#   - event-bus
#  networks:
#   - "lnet"
#   - "rest"
#networks:
#  rest:
#  lnet:
#   external:
#    name: storage_lnet

